[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_speed = 115200

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

[common]
lib_deps =
    arduino-libraries/ArduinoOTA
    bblanchon/ArduinoJson
    paulstoffregen/TimerOne
    cmaglie/FlashStorage
    bblanchon/ArduinoJson@^6.18.5
    id=126
    id=64
